//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PASAROperations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_Customer
    {
        public AF_Customer()
        {
            this.AF_Customer_Val = new HashSet<AF_Customer_Val>();
        }
    
        public int AF_CustomerId { get; set; }
        public string AF_CustomerName { get; set; }
    
        public virtual ICollection<AF_Customer_Val> AF_Customer_Val { get; set; }
    }
}
